version: '3.4'

services:
 db:
    container_name: winter-audit-db
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Pass123!"
      - "ACCEPT_EULA=Y"
    ports:
      - "1433:1433"
 app:
   container_name: winter-audit
   build: 
      dockerfile: ./WebApi/Dockerfile
   depends_on:
     - db
   ports:
     - "8080:80"